### ISSUE TITLE
增加从addon中的script调用LL相关API的功能

### ISSUE THREAD

**Issue by cuixiang0130** [LiteLDev/LeviLamina#1213]
### 您的建议是否与现存的某个问题相关?请描述问题?

Addon中的Script API受官方支持，但缺失部分功能。

1、缺少文件、网络相关接口，并且似乎官方不打算加入文件相关API，网络接口目前是残废状态
2、使用Script API并不能直接修改NBT数据，一些功能仍然需要以非常别扭的方式实现
3、一些功能以js实现非常低效 

### 您认为还缺少什么?如何解决您的问题?

增加从Addon的脚本调用LL提供的API的功能
通过hook相关函数拿到Quickjs的JSContext*，增加API的绑定（也许能通过ScriptX实现，复用部分代码？）,对其做了一点测试
https://github.com/cuixiang0130/add-module-to-addon

**Comment by cuixiang0130** [comment]
官方的模块里各种js对象都通过JS_SetOpaque绑定了native对象，也许最终能做到Player之类的对象互通？

**Comment by WangYneos** [comment]
LL3计划内，请耐心等待（预计暑假）。如果您有好的方案，欢迎pr

**Comment by cuixiang0130** [comment]
如果只导出特定的部分C函数，感觉并不会造成很严重的命名空间污染，毕竟quickjs的函数命名基本以JS_开头，不太可能重复。放到一个命名空间内使用GetProcAddress动态查找函数地址似乎有点增加了复杂度。不过，要是非常在意这个也确实是个问题。

**Comment by cuixiang0130** [comment]
说到命名冲突，ScriptX现在似乎没有注册模块的功能，导出的类和函数也是在全局作用域，不做稍大的修改感觉好像不太能利用好quickjs提供的ES的模块功能

**Comment by cuixiang0130** [comment]
ScriptX 通过 EngineScope内的thread local变量去拿engine得到context，而Quickjs本身的API注册的函数可以直接拿到JSContext。Script X这样的设计使得想要融入Minecraft本身的脚本系统，必须要在执行有调用native层的脚本的函数前构造EngineScope，这样需要多hook一些函数，目前似乎只有两个函数，也增加了维护的难度，EngineScope这样的设计在Script X感觉也很难更改

**Comment by WangYneos** [comment]
> 如果只导出特定的部分C函数，感觉并不会造成很严重的命名空间污染，毕竟quickjs的函数命名基本以JS_开头，不太可能重复。放到一个命名空间内使用GetProcAddress动态查找函数地址似乎有点增加了复杂度。不过，要是非常在意这个也确实是个问题。

污染的是linkage time的命名空间，这个问题不小，可能导致真正的quickjs链不上

**Comment by WangYneos** [comment]
> 说到命名冲突，ScriptX现在似乎没有注册模块的功能，导出的类和函数也是在全局作用域，不做稍大的修改感觉好像不太能利用好quickjs提供的ES的模块功能

这个没办法，加点__internal之类的标志，然后外部通过baselib访问

**Comment by WangYneos** [comment]
> ScriptX 通过 EngineScope内的thread local变量去拿engine得到context，而Quickjs本身的API注册的函数可以直接拿到JSContext。Script X这样的设计使得想要融入Minecraft本身的脚本系统，必须要在执行有调用native层的脚本的函数前构造EngineScope，这样需要多hook一些函数，目前似乎只有两个函数，也增加了维护的难度，EngineScope这样的设计在Script X感觉也很难更改

做点编译期操作来实现吧，这个问题应该不是特别大

**Comment by cuixiang0130** [comment]
有node了再支持Quickjs做script x的后端好像意义不大？（手动狗头）这样可能需要维护两个Quickjs后端了。关于EngineScope，我看了看Script X的源码发现在调用传入的callback前是已经拿到engine了，改一下Script X在调用前构造EngineScope应该就能解决。

**Comment by WangYneos** [comment]
> 有node了再支持Quickjs做script x的后端好像意义不大？（手动狗头）这样可能需要维护两个Quickjs后端了。关于EngineScope，我看了看Script X的源码发现在调用传入的callback前是已经拿到engine了，改一下Script X在调用前构造EngineScope应该就能解决。

hmm，可以让quickjs的引擎和bds内那个一致，共享一份头文件，剩下的改改启动代码吧quickjs做了顺便把bds内绑定带上

**Comment by OEOTYAN** [comment]
这边有进展吗
