### ISSUE TITLE
[Bug]: LL的部分API出现了问题

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LeviLamina#1392]
### Describe the bug

LL版本：2.16.2，BDS版本：1.20.31
出现了如下报错：

https://www.minebbs.com/threads/sidebardesigner-_.17113/page-2#post-138244
 
![4CF7I4ZBGY6@)QCIW){LW8P](https://github.com/LiteLDev/LeviLamina/assets/99462074/b5fe5db1-0c98-4068-a043-fe0a87404afa)

该报错在 [版本BDS1.20.20] 中没有出现过，在1.20.31中出现多次，多数是在玩家初次进服时报错，偶尔也会时不时报错，插件代码并没有问题，money计分板存在并且有分数，而且实际上貌似并没有影响游戏内容，但是控制台就是会疯狂报错，怀疑是LL的API出现了问题

如果是正常情况下插件代码出现了问题那报错不应该出现：
C++ Uncaught Exception Detect
SEH_UNKNOW_ERROR

如果LL2中不打算修复或更新，那希望在LL3中这个bug也能被一并修复，感谢各位开发者的付出！

### To Reproduce

插件内调用.getScore

### Expected behavior

.getScore正常被调用

### Screenshots

![4CF7I4ZBGY6@)QCIW){LW8P](https://github.com/LiteLDev/LeviLamina/assets/99462074/b5fe5db1-0c98-4068-a043-fe0a87404afa)

### Platform

Windows 10

### Version

Windows 10

**Comment by yufengya0420** [comment]
![image](https://github.com/LiteLDev/LeviLamina/assets/99462074/d498a633-68f4-420b-9eb6-e4cc85bef4e5)

setScore addScore getScore 都有问题

**Comment by yufengya0420** [comment]
> ![image](https://user-images.githubusercontent.com/99462074/282237814-d498a633-68f4-420b-9eb6-e4cc85bef4e5.png)
> 
> setScore addScore getScore 都有问题

甚至经济系统也出现了问题
![image](https://github.com/LiteLDev/LeviLamina/assets/99462074/6dd2ae83-60bd-4f21-94b7-4d30c009494e)

**Comment by ShrBox** [comment]
LiteLoaderBDS v2 has been archived, btw, this repository belongs to LeviLamina, don't create issues about LiteLoaderBDS v2.

**Comment by GanchengCat** [comment]
秀 反正我跑路了 运行3个月 懒得维护了
