### ISSUE TITLE
[Bug]: stop无法正常关服（已补充崩服日志）

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LeviLamina#1491]
### Describe the bug

![PUVFTI4K 2)0QG`{~`0(FAI](https://github.com/LiteLDev/LeviLamina/assets/99462074/dc255e2f-fc76-42d0-a8f6-01335e25ca39)

stop后服务器未正常关闭，出现崩溃，崩服日志：
[crash.zip](https://github.com/LiteLDev/LeviLamina/files/14651846/crash.zip)

### To Reproduce

stop

### Expected behavior

正常关服

### Screenshots

![PUVFTI4K 2)0QG`{~`0(FAI](https://github.com/LiteLDev/LeviLamina/assets/99462074/e3608c5d-f815-4b54-9398-10dd118ee7fa)

### Platform

Win10

### Version

0.9.5

**Comment by BensonChen2456** [comment]
Use the FishingAC can solve this problem.

**Comment by OEOTYAN** [comment]
插件问题
