### ISSUE TITLE
[Feature]: 希望加回LL2的配置项ForceUtf8Input

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LeviLamina#1492]
### Is your feature request related to a problem? Please describe.

希望加回LL2的配置项ForceUtf8Input

### Describe the solution you'd like

希望加回LL2的配置项ForceUtf8Input

### Describe alternatives you've considered

希望加回LL2的配置项ForceUtf8Input

### Additional context

希望加回LL2的配置项ForceUtf8Input

**Comment by OEOTYAN** [comment]
听不懂 这干什么的 有什么用

**Comment by yufengya0420** [comment]
> 听不懂 这干什么的 有什么用

LL2的配置文件有这个，LL3没有，开启了可以让BDS控制台强制输入utf8格式的字符，可以让serein类似面板输入指令，否则在serein面板输入任何指令无效

**Comment by XiaoXiaoYang233** [comment]
https://www.minebbs.com/resources/unicodefixer.6991/

**Comment by OEOTYAN** [comment]
<img width="467" alt="image" src="https://github.com/LiteLDev/LeviLamina/assets/58554322/1784821f-74bf-4a76-b39d-c06dbdc36232">
为啥呢

**Comment by OEOTYAN** [comment]
> [ources/unicodefixer.6991/](https://www.minebbs.com/resources/unicodefixer.6991/)

咋我试不出来

**Comment by XiaoXiaoYang233** [comment]
面板

**Comment by Redbeanw44602** [comment]
为什么不让面板适配
