### ISSUE TITLE
[Bug]: stop关服时间等待过长

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LeviLamina#1497]
### Describe the bug

![image](https://github.com/LiteLDev/LeviLamina/assets/99462074/df55a0d0-5209-4f99-aeb2-5546122a28f8)
stop关服时间等待过长

### To Reproduce

stop

### Expected behavior

关服时间短一些

### Screenshots

![image](https://github.com/LiteLDev/LeviLamina/assets/99462074/0f017121-5ad5-4c12-838b-918ed5fc3a2d)

### Platform

Win10

### Version

0.9.5

**Comment by yufengya0420** [comment]
有时候要等好几分钟才能关

**Comment by ShrBox** [comment]
？

**Comment by yufengya0420** [comment]
0.9.4之前的版本关服都很快，就0.9.5开始就非常慢

**Comment by ShrBox** [comment]
请提供安装的插件列表，此问题无法在我的任何环境中复现

**Comment by yufengya0420** [comment]
> 请提供安装的插件列表，此问题无法在我的任何环境中复现

![image](https://github.com/LiteLDev/LeviLamina/assets/99462074/b55cdbbf-b2b9-4e54-a736-3142c8abe002)

有时很快有时非常慢
