### ISSUE TITLE
lxl.require 假死

### ISSUE THREAD

**Issue by niannianqi** [LiteLDev/LeviLamina#221]
**Describe the bug**
以简明清晰的语言描述问题。
在使用ll后bds会不定期卡死

**To Reproduce**
在这里描述如何复现问题。
Steps to reproduce the behavior
开服。。等着

**Expected behavior**
在这里描述你希望看到的现象。
给个解决方案

**Screenshots or log**
请提供一些屏幕截图，或者相关日志（这很必要）。
If applicable, add screenshots or log to help explain your problem.
![5W`ZYXIUW45MYS_DRLXO18E](https://user-images.githubusercontent.com/63998607/153711184-9d5fcc8d-a946-4064-9255-dce0be600975.png)
![XAY(RUW8_CU 1P$1_FNN1@M](https://user-images.githubusercontent.com/63998607/153711190-935a7a75-18d4-42a7-99f3-19acce7b5cde.png)

**Environment (please complete the following information):**
 - OS: win10家庭版
 - LiteLoader Version 最新版

**Additional content**
附加信息
Add any other content about the problem here.

**Comment by Jaciezyt** [comment]
装了哪些插件？你先排查看看？
还有，不要点击控制台，那样会导致进程暂停，注意控制台标题“选择”

**Comment by niannianqi** [comment]
> 装了哪些插件？你先排查看看？ 还有，不要点击控制台，那样会导致进程暂停，注意控制台标题“选择”

排查了，是菜单插件的问题，我看有个issue提了，就是菜单插件可以在选项前添加图片，有图片就有几率假死，我把服务器菜单改成无图就解决了卡死的问题
控制台是截图的时候点的

**Comment by dreamguxiang** [comment]
啥样子的图片
iland表单的图片并未发现问题

**Comment by yufengya0420** [comment]
本地图片应该没事吧，我菜单也有图片但是无假死，估计是URL那种

**Comment by niannianqi** [comment]
确实是url的链接图片

**Comment by niannianqi** [comment]
刚试了一下本地图片也有这个问题

**Comment by niannianqi** [comment]
[data.txt](https://github.com/LiteLDev/LiteLoaderBDS/files/8053421/data.txt)
这个是我菜单的json

**Comment by yufengya0420** [comment]
顺便排查一下lxl.import？这个远程调用貌似会导致websocket使控制台假死

**Comment by yqs112358** [comment]
图片卡服多半是BDS自己的问题，加载器这里代码没动过

**Comment by dreamguxiang** [comment]
> 顺便排查一下lxl.import？这个远程调用貌似会导致websocket使控制台假死

抓一下假死的dmp

**Comment by yqs112358** [comment]
我马上看import

**Comment by yqs112358** [comment]
lxl.import目测看不出问题，卡服的时候后台有输出内容吗

**Comment by niannianqi** [comment]
> lxl.import目测看不出问题，卡服的时候后台有输出内容吗

没有日志输出，直接卡死

**Comment by yqs112358** [comment]
请给出更多信息，如dump文件，WPR分析数据等
这里无法复现

**Comment by yufengya0420** [comment]
咋上传dump文件的

**Comment by Jaciezyt** [comment]
直接复制到输入框即可

**Comment by yufengya0420** [comment]
zip上传不了？

**Comment by Jaciezyt** [comment]
好吧gh确实不支持dmp文件

**Comment by Jaciezyt** [comment]
> zip上传不了？

zip是支持的，你可以看看

**Comment by yufengya0420** [comment]
发LiteLoaderBDS交流2群了

**Comment by yufengya0420** [comment]
147MB的zip上传不了

**Comment by yufengya0420** [comment]
wpr等我下次假死再保存

**Comment by yqs112358** [comment]
你可以用网盘或者文叔叔之类的工具

**Comment by yufengya0420** [comment]
这是dump文件链接：
我用夸克网盘分享了「bedrock_server_mod.exe_220213_004955.zip」，点击链接即可保存。打开「夸克APP」
链接：https://pan.quark.cn/s/7aa5bda3d8e5

**Comment by yufengya0420** [comment]
完整的假死文件：我用夸克网盘分享了「假死排查.zip」，点击链接即可保存。打开「夸克APP」，
链接：https://pan.quark.cn/s/562b10761ec5

**Comment by yqs112358** [comment]
来群里看看：https://jq.qq.com/?_wv=1027&k=og3LkDgk

**Comment by yqs112358** [comment]
谢谢你的合作，已经修复完毕 
请入群领取已修复的版本，或者等待下个正式版本更新
