### ISSUE TITLE
'Event::addEventListener': none of the 16 overloads could convert all the argument types. Help pls

### ISSUE THREAD

**Issue by krusalovorg** [LiteLDev/LeviLamina#23]
```
    Event::addEventListener([](PlayerUseCmdEV ev) {
        std::string name = ev.Player->getNameTag();
        LOG("       Player Use Cmd");
        LOG("------------------------------");
        LOG("| NickName: " + name);
        LOG("| CMD: " + ev.cmd);
        LOG("| Result: " + ev.mc_result);
        LOG("------------------------------");
    });

```Severity	Code	Description	Project	File	Line	Suppression State
Error	C2665	'Event::addEventListener': none of the 16 overloads could convert all the argument types

**Comment by ShrBox** [comment]
try `return true;`

**Comment by krusalovorg** [comment]
Thanks! It is work!
Is it possible to change the chat message? How to execute command via dll mod?

**Comment by ShrBox** [comment]
> Thanks! It is work!
> Is it possible to change the chat message? How to execute command via dll mod?

`liteloader::runcmd`
if you want to hide the command output, you can use `liteloader::runcmdEx`

**Comment by ShrBox** [comment]
> Thanks! It is work!
> Is it possible to change the chat message? How to execute command via dll mod?

you can read:https://github.com/LiteLDev/LiteLoaderBDS/blob/f5bf9131918b17dfdba88c0d89f054ba30a6a1e2/LiteLoader/api/Basic_Event.cpp#L52

**Comment by krusalovorg** [comment]
Is there an example of a mod using Api Thook LiteLoader?

**Comment by ShrBox** [comment]
> Is there an example of a mod using Api Thook LiteLoader?

https://github.com/ShrBox/FuckWither/blob/2b53cfa7219a05034f993711be0ff2389340f9e2/FuckWither/FuckWither.cpp#L44
https://github.com/ShrBox/ThirstPoint/blob/eb42922f01a397d8055cc1a437ca192019a00c29/ThirstPoint_LiteLoader/ThirstPoint.cpp#L120

**Comment by krusalovorg** [comment]
Thank you! You helped me a lot!

**Comment by krusalovorg** [comment]
How do I get gamer tags?

**Comment by ShrBox** [comment]
> How do I get gamer tags?

Currently LiteLoader does not have this function, but you can find related functions through IDA Pro reverse analysis of the Windows and Linux versions of Bedrock Dedicated Server
