### ISSUE TITLE
希望新增更多的函数

### ISSUE THREAD

**Issue by ChenDoXiu** [LiteLDev/LeviLamina#246]
希望增加
- 实体被创建的回调
- 区块第一次生成时的回调
- 随机刻和游戏刻相关回调
- 自定义维度相关

**Comment by yqs112358** [comment]
收到你的反馈
前三者应该是可以正常加入的
第四个API由于涉及到过多的底层机制，可能无法在近期实现
还是感谢你的反馈

**Comment by ChenDoXiu** [comment]
感谢

**Comment by leoweyr** [comment]
自定义维度的话，我觉得不太现实。那东西现在Minecraft Java版官方都有在做的测试功能。你可以使用多世界的概念来补充（虽然多开服务器这可能会多耗资源）。所以我也在想能不能单个liteloader多开BDS地图，也可以转化为多开BDS

**Comment by yqs112358** [comment]
确实可以通过多进程+跨服传送来实现多世界，关于相关的性能问题我们这里有过一定的研究

**Comment by leoweyr** [comment]
多世界我现在能知道的方法本质就是多开bds，但是如果多开的bds都运行同样的ll加载器和lxl插件平台，消耗资源多。如果能运行单个ll和lxl的同时运行多个bds就好了，然后插件的话可以设置配置文件指向对应需要的bds

**Comment by leoweyr** [comment]
我虽然不能提供技术支持，但我提供一些个人的设计思路支持。继上面的想法，如果lxl和ll对bds是通道性服务的话，是可以实现lxl和ll服务多个bds，但如果是一对一私人定制服务的话，可能就得一对一bds，那么资源浪费的陈述就不成立。经过一定思考，我觉得lxl和ll的工作模式是后者？

**Comment by Redbeanw44602** [comment]
当然是后者，再说本身消耗资源的大头是BDS而非加载器或插件。

**Comment by Dofes** [comment]
多世界本身问题,emm,不好实现,但是be还是有实现的,比如ic,就是比较困难吧(

**Comment by yqs112358** [comment]
抱歉，这个适配1.18的版本由于期末考试临近，仅作简单适配工作，不增加新接口
新接口将会在寒假到来
