### ISSUE TITLE
Running on Linux Ubuntu

### ISSUE THREAD

**Issue by KocTu4eK** [LiteLDev/LeviLamina#26]
Can’t start RoDB.exe with wine. Is it even possible to run it on Ubuntu?
P.S. Mono can launch only .NET programs.

Wine error:

root@localhost:~/LiteLoader# wine RoDB.exe
it looks like wine32 is missing, you should install it.       as root, please execute "apt-get install wine32"
0020:err:plugplay:deviceloop_thread Can't init SDL: Could not initialize UDEV
0009:err:module:__wine_process_init L"Z:\\root\\LiteLoader\\RoDB.exe" not supported on this system

**Comment by ShrBox** [comment]
RoDB.exe cannot run in wine, please run on Windows or ask others for symdb

**Comment by KocTu4eK** [comment]
> RoDB.exe cannot run in wine, please run on Windows or ask others for symdb

I thought so. Thanks for the answer. I wanted to ask my friend for a SymDB, but he said that this would not work.
