### ISSUE TITLE
Http重载报错

### ISSUE THREAD

**Issue by timiya233** [LiteLDev/LeviLamina#265]
### Exceptions module 异常模块

ScriptEngine 脚本引擎

### Operating System 操作系统

Windows 10

### LiteLoader version   LiteLoader版本

2.1.2

### BDS version   BDS版本

1.18.11

### What happened? 发生了什么问题?

http操作在重载插件的情况下报错

### Steps to reproduce? 复现此问题的步骤

1.创建test.js
2.写入network.httpGet(xxx,xxxx);
3.加载插件，在http结果未返回时reload插件

### Relevant log output 有关的日志/输出

```shell
21:22:46 ERROR [LiteLoader] HttpGet Callback Failed!
21:22:46 ERROR [LiteLoader] Uncaught Exception Detected!
```

### Plugin list 插件列表

无关痛痒

**Comment by Redbeanw44602** [comment]
#253
