### ISSUE TITLE
Api LiteLoader

### ISSUE THREAD

**Issue by krusalovorg** [LiteLDev/LeviLamina#27]
Is it possible to get the name of the block by the coordinates by getting them from the player(`player->getPos()`)?

**Comment by KawaiiNahida** [comment]
First you should get the Pointer of the Block  
Or get the BlockSource Pointer, you will be able to call mc function to get pBlk
`Block& BlockSource::getBlock(Blocksource& this, BlockPos bpos)`
```
Block* pBlk = SymCall("?getBlock@BlockSource@@QEBAAEBVBlock@@AEBVBlockPos@@@Z", Block*, BlockSource*, BlockPos*)(bs, bpos);
auto bname = offBlock::getFullName(pBlk);//using offset
```

**Comment by KawaiiNahida** [comment]
By the way, the position of the player is always air, you may want to get the Block of 
`{PlayerPos.x, PlayerPos.y-1, PlayerPos.z}`

**Comment by krusalovorg** [comment]
![image](https://user-images.githubusercontent.com/70585437/118648576-9b937400-b7f3-11eb-8444-a7dcd6032231.png)
new api

**Comment by krusalovorg** [comment]
![image](https://user-images.githubusercontent.com/70585437/118648644-af3eda80-b7f3-11eb-8a49-8b20de7b3a63.png)

**Comment by KawaiiNahida** [comment]
> ![image](https://user-images.githubusercontent.com/70585437/118648576-9b937400-b7f3-11eb-8444-a7dcd6032231.png)
> new api

Have you include mc/offsetHeler.h ?  
or you include the file twice in your project?   
It seems it's a grammar mistake that you made

**Comment by KawaiiNahida** [comment]
By the way, BlockLegacy and Block are two different type. you cannot converent by `(BlockSource*)(Block*)pBlk`

**Comment by krusalovorg** [comment]
how to get bs?
