### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by TerrOreIst** [LiteLDev/LeviLamina#39]
Hello. Maybe I'm not the only one with this problem. I have encountered a RAM leak in LiteLoader. How can I fix this?

**Comment by dreamguxiang** [comment]
Did you encounter it immediately after turning on the server?

**Comment by ghost** [comment]
Please provide detailed info about your runtime environment.
Do you use wine?
How did you detect memory leak?

**Comment by TerrOreIst** [comment]
I'm using a regular windows 10. The server takes up RAM, but it does not clear it after that. Let's say if you put a spawn machine here, it will load all the RAM after some time.

**Comment by ghost** [comment]
> windows

BDS also has memory leak.So it will be better if you can use profiling tools to find out who causes the problen.

**Comment by TerrOreIst** [comment]
Yes, it turns out that the BDS
 has it...
this is very bad. 
sorry, I thought it was a lite loader because the technical admin said that it was.  It seems he was wrong. 
You don't know how to fix a leak in BDS?

**Comment by TerrOreIst** [comment]
A regular BDS takes a lot of RAM, but it still cleans up a little. I didn't notice this with Lite Loader...

**Comment by Redbeanw44602** [comment]
So how much RAM do you have?

**Comment by TerrOreIst** [comment]
12 gb ddr4
I'm already going to switch to BDSX

**Comment by dreamguxiang** [comment]
Thanks for your feedback
