### ISSUE TITLE
［内存溢出］使用wine运行liteloader崩溃

### ISSUE THREAD

**Issue by X-Funny** [LiteLDev/LeviLamina#41]
使用wine运行支持1.17.10版本的liteloader崩溃。已经在Windows10上生成symdb2文件
崩溃原因:out of memory
操作系统:ubuntu20.04
wine版本:6.0.1
服务器配置1核1G
如果运行支持上一个minecraftpe版本的liteloader和bds（1.17.02）是可以正常运行的
下面是情景复现:
root@iZbp17cqlbtdmgdupgbdx9Z:/mcserver/mcbe1# wine bedrock_server.exe
003c:err:service:validate_service_config Service L"clr_optimization_v4.0.30319_32" - SERVICE_BOOT_START and SERVICE_SYSTEM_START are only allowed for driver services
003c:err:service:scmdatabase_load_services Invalid configuration of service L"clr_optimization_v4.0.30319_32" - skipping
003c:err:service:validate_service_config Service L"clr_optimization_v4.0.30319_64" - SERVICE_BOOT_START and SERVICE_SYSTEM_START are only allowed for driver services
003c:err:service:scmdatabase_load_services Invalid configuration of service L"clr_optimization_v4.0.30319_64" - skipping
0098:err:explorer:initialize_display_settings Failed to query current display settings for L"\\\\.\\DISPLAY1".
[Info] Loading Symbols
已杀死
root@iZbp17cqlbtdmgdupgbdx9Z:/mcserver/mcbe1#

有针对wine可行的解决方案吗，还是此版本存在bug？

**Comment by X-Funny** [comment]
补充一点:运行官方最新ubuntu版本的bds是能正常运行的

**Comment by ShrBox** [comment]
新版本LiteLoader开服会占用大约80m的内存用于存储符号数据，加上bds自身占用大约200m，开服时服务器的内存是否足够?
之前我在容器里遇到过类似的问题，开服时内存占用会突然到1g，开服后又恢复正常，似乎只有wine会出现这个bug

**Comment by KawaiiNahida** [comment]
FastDlsym在初始化时会产生大量临时变量，但wine似乎不会在过程中自己回收（在Windows上会），，，，建议使用内存超过1.5G的机器开服

**Comment by X-Funny** [comment]
内存是足够的，运行bedrockserver.exe后的5秒钟内服务器内存还剩1200MB(之前说错了，我的服务器运存是有2G)，但在系统杀进程的前一秒CPU占用瞬间达到了98%，但崩溃日志里报的是out of memory

**Comment by KawaiiNahida** [comment]
![图片](https://user-images.githubusercontent.com/42824603/126642285-0b14e3b0-de83-4148-a667-21908fe284ce.png)
我想，问题出在这里，今后我看下改进方案，暂时不清楚具体其他问题，但是wine的内存管理和原生Windows有差别没得逃（毕竟win下1.1g，1.2g的可用空间其实应该是够的，并且我相信linux没干别的话应该可用空间其实更多）

**Comment by KawaiiNahida** [comment]
在bds目录```touch LiteLoaderDevMode```关掉FastDlsym看看？需要最新LiteLoader，但是这样线程不安全，虽然崩服概率也不算很大就是

**Comment by X-Funny** [comment]
我现在更新了liteloder，已经不会出现系统杀进程的情况了
