### ISSUE TITLE
The latest action has a command problem

### ISSUE THREAD

**Issue by Jaciezyt** [LiteLDev/LeviLamina#43]
If I use command `version`,it will not output.
And console will get stuck like the picture.
The latest release(`1.0.0`) is OK.
![image](https://user-images.githubusercontent.com/66063199/126805378-943301a8-74fa-4852-b339-dfac9ae5c7aa.png)
(`stop` command can be executed)

**Comment by KawaiiNahida** [comment]
dlsym  has a dead lock which may cause this problem.
Try the latest build plz
