### ISSUE TITLE
wine版本脚本已经过时

### ISSUE THREAD

**Issue by ideaexplorer233** [LiteLDev/LeviLamina#633]
### 异常模块

Core（核心）

### 操作系统

GNU/Linux with wine

### LiteLoader版本

2.4.1

### BDS版本

1.19.11.01

### 发生了什么?

根据[WineHQ文档](https://wiki.winehq.org/Ubuntu_zhcn) 自动安装脚本中的apt-key已经弃用
并且希望能选择不同系统的安装

**Comment by ShrBox** [comment]
81dda7c94f15fa9b2bdda1e4075b6aef4dcb920b
多系统的安装脚本会考虑的
